# Generated by Django 4.2 on 2026-06-18 17:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('functie', models.CharField(blank=True, choices=[('PROCUROR', 'Procuror'), ('OFITER', 'Ofițer de urmărire penală'), ('GREFIER', 'Grefier'), ('ADMIN', 'Administrator sistem')], max_length=20, null=True)),
                ('parafa', models.CharField(blank=True, help_text='Codul de identificare al procurorului/ofițerului', max_length=20, null=True, verbose_name='Parafă')),
                ('otp_configurat', models.BooleanField(default=False, verbose_name='2FA configurat')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dosar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_unic', models.CharField(max_length=50, unique=True, verbose_name='Număr unic dosar')),
                ('data_deschiderii', models.DateField(default=django.utils.timezone.now)),
                ('stare', models.CharField(choices=[('ACTIV', 'Activ'), ('SUSPENDAT', 'Suspendat'), ('INCHIS', 'Închis'), ('CLASAT', 'Clasat')], default='ACTIV', max_length=20)),
                ('infractiune_cercetata', models.CharField(max_length=200, verbose_name='Infracțiunea cercetată')),
                ('descriere', models.TextField(blank=True, null=True)),
                ('infractiune_cercetata_ascii', models.CharField(blank=True, editable=False, max_length=200)),
                ('ofiter_caz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosare_ofiter', to=settings.AUTH_USER_MODEL)),
                ('procuror_caz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosare_procuror', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosar',
                'verbose_name_plural': 'Dosare',
                'ordering': ['-data_deschiderii'],
            },
        ),
        migrations.CreateModel(
            name='StadiuCercetare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('INCEPERE', 'Începerea urmăririi penale'), ('PUNERE_SUB_INVINUIRE', 'Punere sub învinuire'), ('TRIMITERE_JUDECATA', 'Trimitere în judecată'), ('CLASARE', 'Clasare'), ('SUSPENDARE', 'Suspendare')], max_length=50)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observatii', models.TextField(blank=True, null=True)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadii', to='cases.dosar')),
                ('inregistrat_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadiu Cercetare',
                'verbose_name_plural': 'Stadii Cercetare',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ParteImplicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=200)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP')),
                ('calitate', models.CharField(choices=[('SUSPECT', 'Suspect'), ('INCULPAT', 'Inculpat'), ('PARTE_VATAMATA', 'Parte Vătămată'), ('MARTOR', 'Martor'), ('EXPERT', 'Expert')], default='SUSPECT', max_length=30)),
                ('adresa', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nume_complet_ascii', models.CharField(blank=True, editable=False, max_length=200)),
                ('adresa_ascii', models.CharField(blank=True, editable=False, max_length=300)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parti_implicate', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Parte Implicată',
                'verbose_name_plural': 'Părți Implicate',
            },
        ),
        migrations.CreateModel(
            name='MasuraPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('RETINERE', 'Reținere'), ('AREST_PREVENTIV', 'Arest preventiv'), ('CONTROL_JUDICIAR', 'Control judiciar'), ('INTERDICTIE', 'Interdicție')], max_length=30)),
                ('data_start', models.DateField(default=django.utils.timezone.now)),
                ('data_expirare', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('dispusa_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masuri_preventive', to='cases.parteimplicata')),
            ],
            options={
                'verbose_name': 'Măsură Preventivă',
                'verbose_name_plural': 'Măsuri Preventive',
                'ordering': ['-data_start'],
            },
        ),
        migrations.CreateModel(
            name='Infractiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incadrare_juridica', models.CharField(help_text='Ex: Art. 208 Cod Penal — Furt', max_length=200, verbose_name='Încadrare juridică')),
                ('data_comiterii', models.DateField(blank=True, null=True)),
                ('adresa_comiterii', models.CharField(blank=True, max_length=300, null=True)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('incadrare_juridica_ascii', models.CharField(blank=True, editable=False, max_length=200)),
                ('adresa_comiterii_ascii', models.CharField(blank=True, editable=False, max_length=300)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractiuni', to='cases.dosar')),
            ],
            options={
                'verbose_name': 'Infracțiune',
                'verbose_name_plural': 'Infracțiuni',
            },
        ),
    ]
