# Generated by Django 6.0.6 on 2026-06-25 18:58

import cases.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_historicalstadiucercetare_historicalparteimplicata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteimplicata',
            name='cnp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='CNP Hash (index)'),
        ),
        migrations.AddField(
            model_name='parteimplicata',
            name='cnp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='CNP Hash (index)'),
        ),
        migrations.AlterField(
            model_name='historicalparteimplicata',
            name='cnp',
            field=cases.fields.EncryptedField(blank=True, null=True, verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='parteimplicata',
            name='cnp',
            field=cases.fields.EncryptedField(blank=True, null=True, verbose_name='CNP'),
        ),
    ]
