# Generated by Django 6.0.6 on 2026-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_historicalparteimplicata_cnp_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificat_pem',
            field=models.TextField(blank=True, null=True, verbose_name='Certificat public (PEM)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cheie_privata_criptata',
            field=models.BinaryField(blank=True, null=True, verbose_name='Cheie privată (criptată)'),
        ),
    ]
