# Generated by Django 4.2 on 2026-06-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActUrmarire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(blank=True, max_length=255, null=True)),
                ('tip', models.CharField(choices=[('ORDONANTA', 'Ordonanță'), ('REFERAT', 'Referat'), ('DECLARATIE', 'Declarație'), ('PROCES_VERBAL', 'Proces-Verbal'), ('ALTUL', 'Alt tip de act')], default='ORDONANTA', max_length=50)),
                ('fisier', models.FileField(upload_to=documents.models.cale_upload_document, validators=[documents.models.valideaza_extensie_document, documents.models.valideaza_dimensiune_document])),
                ('data_documentului', models.DateField(default=django.utils.timezone.now)),
                ('data_inregistrarii', models.DateField(default=django.utils.timezone.now)),
                ('data_incarcarii', models.DateTimeField(auto_now_add=True)),
                ('descriere_scurta', models.TextField(blank=True, null=True)),
                ('titlu_ascii', models.CharField(blank=True, editable=False, max_length=255)),
                ('descriere_scurta_ascii', models.TextField(blank=True, editable=False)),
                ('fisier_semnat', models.FileField(blank=True, null=True, upload_to='documente/semnate/%Y/%m/')),
                ('este_semnat', models.BooleanField(default=False)),
                ('data_semnarii', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documente', to='cases.dosar')),
                ('semnat_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acte_semnate_de_mine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Act de Urmărire Penală',
                'verbose_name_plural': 'Acte de Urmărire Penală',
                'ordering': ['-data_incarcarii'],
            },
        ),
        migrations.CreateModel(
            name='TrimiterePrinEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimis_la', models.DateTimeField(auto_now_add=True)),
                ('email_destinatar', models.EmailField(max_length=254)),
                ('nume_destinatar', models.CharField(max_length=200)),
                ('subiect', models.CharField(max_length=255)),
                ('mesaj', models.TextField(blank=True)),
                ('reusit', models.BooleanField(default=True)),
                ('varianta_trimisa', models.CharField(choices=[('original', 'Original'), ('semnat', 'Semnat')], default='original', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimiteri_email', to='documents.acturmarire')),
                ('trimis_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailuri_trimise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trimitere Email Document',
                'verbose_name_plural': 'Trimiteri Email Documente',
                'ordering': ['-trimis_la'],
            },
        ),
    ]
