# Generated by Django 4.2 on 2026-06-19 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_historicalstadiucercetare_historicalparteimplicata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActUrmarire',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titlu', models.CharField(blank=True, max_length=255, null=True)),
                ('tip', models.CharField(choices=[('ORDONANTA', 'Ordonanță'), ('REFERAT', 'Referat'), ('DECLARATIE', 'Declarație'), ('PROCES_VERBAL', 'Proces-Verbal'), ('ALTUL', 'Alt tip de act')], default='ORDONANTA', max_length=50)),
                ('fisier', models.TextField(max_length=100, validators=[documents.models.valideaza_extensie_document, documents.models.valideaza_dimensiune_document])),
                ('data_documentului', models.DateField(default=django.utils.timezone.now)),
                ('data_inregistrarii', models.DateField(default=django.utils.timezone.now)),
                ('data_incarcarii', models.DateTimeField(blank=True, editable=False)),
                ('descriere_scurta', models.TextField(blank=True, null=True)),
                ('titlu_ascii', models.CharField(blank=True, editable=False, max_length=255)),
                ('descriere_scurta_ascii', models.TextField(blank=True, editable=False)),
                ('fisier_semnat', models.TextField(blank=True, max_length=100, null=True)),
                ('este_semnat', models.BooleanField(default=False)),
                ('data_semnarii', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dosar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.dosar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semnat_de', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Act de Urmărire Penală',
                'verbose_name_plural': 'historical Acte de Urmărire Penală',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
